name: Audit
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

env:
  go-version: "1.21"

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    name: Build and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}
      - name: Verify dependencies
        run: go mod verify
      - name: Build
        run: go build -v -o bin/ssg cmd/cli/main.go
      - name: Run go vet
        run: go vet ./...
      - name: Run tests
        run: go test -race -vet=off ./...

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.go-version }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
